version: 2
registries:
  maven-google:
    type: maven-repository
    url: "https://maven.google.com"
    replaces-base: true
updates:
  # GitHub Actions in /shared-overwrite/.github/workflows/
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/shared-overwrite/.github/workflows/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
      timezone: "America/Montreal"
    target-branch: "mmathieum"
    groups:
      gh-actions:
        patterns:
          - "actions/*"
    open-pull-requests-limit: 7
  # Gradle in /gradle/libs.versions.toml
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - maven-google
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
      timezone: "America/Montreal"
    target-branch: "mmathieum"
    groups:
      kotlin-ksp-compose:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlinx:*"
          - "org.jetbrains.kotlin.jvm"
          - "org.jetbrains.kotlin.android"
          - "com.google.devtools.ksp"
          - "androidx.compose.compiler:compiler"
      androidx:
        patterns:
          - "androidx*:*"
          - "com.google.android.material:material"
      gms:
        patterns:
          - "com.google.android.gms:*"
          - "com.google.firebase:*"
      play:
        patterns:
          - "com.android.billingclient:*"
          - "com.google.android.play:*"
      ads:
        patterns:
          - "com.google.android.ads:*"
          - "com.google.ads.mediation:*"
      maps:
        patterns:
          - "com.google.maps.android:*"
      protobuf:
        patterns:
          - "com.google.protobuf:*"
      apache-commons:
        patterns:
          - "org.apache.commons:*"
      di:
        patterns:
          - "com.google.dagger:*"
      dev:
        patterns:
          - "com.squareup.leakcanary:*"
      gradle-updater:
        patterns:
          - "com.github.ben-manes.versions"
          - "nl.littlerobots.version-catalog-update"
      network:
        patterns:
          - "com.squareup.okhttp3:*"
          - "com.github.chuckerteam.chucker:*"
          - "com.google.code.gson:gson"
          - "com.github.bumptech.glide:*"
          - "com.caverock:androidsvg-aar"
      test:
        patterns:
          - "junit:*"
          - "org.mockito:*"
    open-pull-requests-limit: 7
