version: 2
updates:
  # GitHub Actions in /shared-overwrite/.github/workflows/
  - package-ecosystem: "github-actions"
    directory: "/shared-overwrite/.github/workflows/"
    schedule:
      interval: "weekly"
  # Gradle in /gradle/libs.versions.toml
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
