version: 2
registries:
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"
updates:
  # GitHub Actions in /shared-overwrite/.github/workflows/
  - package-ecosystem: "github-actions"
    directory: "/shared-overwrite/.github/workflows/"
    schedule:
      interval: "weekly"
    target-branch: "mmathieum"
    groups:
      gh-actions:
        patterns:
          - "actions/*"
    open-pull-requests-limit: 7
  # Gradle in /gradle/libs.versions.toml
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "mmathieum"
    groups:
      kotlin-ksp-compose:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.jvm"
          - "com.google.devtools.ksp"
          - "androidx.compose.compiler:compiler"
    open-pull-requests-limit: 7
