#!/bin/bash
SCRIPT_DIR="$(dirname "$0")";

ROOT_DIR="$SCRIPT_DIR/../../../../..";
COMMONS_DIR="${ROOT_DIR}/commons";
source ${COMMONS_DIR}/commons.sh;

setIsCI;

echo ">> Generating AndroidManifest.xml...";

APP_ANDROID_DIR="${ROOT_DIR}/app-android";
SRC_DIR="${APP_ANDROID_DIR}/src";
MAIN_DIR="${SRC_DIR}/main";
#DEBUG_DIR="${SRC_DIR}/debug";
ANDROID_MANIFEST_DIR="${MAIN_DIR}";
# ANDROID_MANIFEST_DIR="${DEBUG_DIR}"; #DEBUG
ANDROID_MANIFEST_FILE="${ANDROID_MANIFEST_DIR}/AndroidManifest.xml";
mkdir -p "${ANDROID_MANIFEST_DIR}";
checkResult $?;
if [ -f "${ANDROID_MANIFEST_FILE}" ]; then
  echo ">> File '$ANDROID_MANIFEST_FILE' already exist."; # compat with existing AndroidManifest.xml
  exit 0; # compat w/ manually created file
fi
rm -f "${ANDROID_MANIFEST_FILE}";
checkResult $?;
touch "${ANDROID_MANIFEST_FILE}";
checkResult $?;

cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
<?xml version="1.0" encoding="utf-8"?>
<!-- DO NOT EDIT: this file is generated by MTAndroidManifest.xml.MT.sh -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    tools:ignore="MissingVersion">

    <application
        android:description="@string/app_desc"
        android:icon="@mipmap/module_app_icon"
        android:label="@string/app_name"
EOL

NETWORK_SECURITY_CONFIG_FILE="${MAIN_DIR}/res/xml/network_security_config.xml";
if [ -f "${NETWORK_SECURITY_CONFIG_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        android:networkSecurityConfig="@xml/network_security_config"
EOL
fi

cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        tools:targetApi="\${target_sdk_version}">
EOL

RES_VALUES_DIR="${MAIN_DIR}/res/values";

BIKE_STATION_FILE="${RES_VALUES_DIR}/bike_station_values.xml";
if [ -f "${BIKE_STATION_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        <!-- BIKE STATIONS PROVIDER -->
        <provider
            android:name="org.mtransit.android.commons.provider.GBFSProvider"
            android:authorities="@string/bike_station_authority"
            android:exported="true"
            android:readPermission="\${permission_provider_read}"
            tools:ignore="MissingRegistered">
            <meta-data
                android:name="@string/agency_provider"
                android:value="@string/agency_provider" />
            <meta-data
                android:name="@string/agency_provider_type"
                android:value="@integer/bike_station_agency_type" />
            <meta-data
                android:name="@string/poi_provider"
                android:value="@string/poi_provider" />
            <meta-data
                android:name="@string/status_provider"
                android:value="@string/status_provider" />
            <meta-data
                android:name="@string/status_provider_target"
                android:value="@string/bike_station_status_for_poi_authority" />
        </provider>
EOL
fi

GTFS_FILE="${RES_VALUES_DIR}/gtfs_rts_values_gen.xml"; # do not change to avoid breaking compat w/ old modules
if [ -f "${GTFS_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        <!-- GTFS ROUTE DIRECTION STOP & SCHEDULE PROVIDER -->
        <provider
            android:name="org.mtransit.android.commons.provider.GTFSProvider"
            android:authorities="@string/gtfs_rts_authority"
            android:exported="true"
            android:readPermission="\${permission_provider_read}"
            tools:ignore="MissingRegistered">
            <meta-data
                android:name="@string/agency_provider"
                android:value="@string/agency_provider" />
            <meta-data
                android:name="@string/agency_provider_type"
                android:value="@integer/gtfs_rts_agency_type" />
            <meta-data
                android:name="@string/poi_provider"
                android:value="@string/poi_provider" />
            <meta-data
                android:name="@string/status_provider"
                android:value="@string/status_provider" />
            <meta-data
                android:name="@string/status_provider_target"
                android:value="@string/gtfs_status_for_poi_authority" />
            <meta-data
                android:name="@string/rts_provider"
                android:value="@string/rts_provider" />
            <meta-data
                android:name="@string/schedule_provider"
                android:value="@string/schedule_provider" />
            <meta-data
                android:name="@string/schedule_provider_target"
                android:value="@string/gtfs_rts_authority" />
        </provider>
EOL
fi

EXPORT_VEHICLE_LOCATION_PROVIDER=false;
# EXPORT_VEHICLE_LOCATION_PROVIDER=true; # WIP

GTFS_RT_FILE="${RES_VALUES_DIR}/gtfs_real_time_values.xml";
if [ -f "${GTFS_RT_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        <!-- GTFS REAL TIME PROVIDER -->
        <provider
            android:name="org.mtransit.android.commons.provider.GTFSRealTimeProvider"
            android:authorities="@string/gtfs_real_time_authority"
            android:exported="true"
            android:readPermission="\${permission_provider_read}"
            tools:ignore="MissingRegistered">
EOL
  if grep -q "gtfs_real_time_agency_service_alerts_url" "${GTFS_RT_FILE}"; then
    cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
            <meta-data
                android:name="@string/service_update_provider"
                android:value="@string/service_update_provider" />
            <meta-data
                android:name="@string/service_update_provider_target"
                android:value="@string/gtfs_real_time_for_poi_authority" />
EOL
  fi

  if grep -q "gtfs_real_time_agency_vehicle_positions_url" "${GTFS_RT_FILE}"; then
    if [[ ${EXPORT_VEHICLE_LOCATION_PROVIDER} == true ]]; then
      cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
            <meta-data
                android:name="@string/vehicle_location_provider"
                android:value="@string/vehicle_location_provider" />
            <meta-data
                android:name="@string/vehicle_location_provider_target"
                android:value="@string/gtfs_real_time_for_poi_authority" />
EOL
    fi
  fi

  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        </provider>
EOL
fi

STRATEGIC_MAPPING_FILE="${RES_VALUES_DIR}/strategic_mapping_values.xml";
if [ -f "${STRATEGIC_MAPPING_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        <!-- STRATEGIC MAPPING PROVIDER -->
        <provider
            android:name="org.mtransit.android.commons.provider.StrategicMappingProvider"
            android:authorities="@string/strategic_mapping_authority"
            android:exported="true"
            android:readPermission="\${permission_provider_read}"
            tools:ignore="MissingRegistered">
            <meta-data
                android:name="@string/status_provider"
                android:value="@string/status_provider" />
            <meta-data
                android:name="@string/status_provider_target"
                android:value="@string/strategic_mapping_status_for_poi_authority" />
        </provider>
EOL
fi

NEXT_BUS_FILE="${RES_VALUES_DIR}/next_bus_values.xml";
if [ -f "${NEXT_BUS_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        <!-- NEXT BUS PROVIDER -->
        <provider
            android:name="org.mtransit.android.commons.provider.NextBusProvider"
            android:authorities="@string/next_bus_authority"
            android:exported="true"
            android:readPermission="\${permission_provider_read}"
            tools:ignore="MissingRegistered">
            <meta-data
                android:name="@string/service_update_provider"
                android:value="@string/service_update_provider" />
            <meta-data
                android:name="@string/service_update_provider_target"
                android:value="@string/next_bus_for_poi_authority" />
            <meta-data
                android:name="@string/status_provider"
                android:value="@string/status_provider" />
            <meta-data
                android:name="@string/status_provider_target"
                android:value="@string/next_bus_for_poi_authority" />
EOL
  if [[ ${EXPORT_VEHICLE_LOCATION_PROVIDER} == true ]]; then
    cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
             <meta-data
                android:name="@string/vehicle_location_provider"
                android:value="@string/vehicle_location_provider" />
            <meta-data
                android:name="@string/vehicle_location_provider_target"
                android:value="@string/next_bus_for_poi_authority" />
EOL
  fi
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        </provider>
EOL
fi

CA_EDMONTON_PROVIDER_FILE="${RES_VALUES_DIR}/ca_edmonton_values.xml";
if [ -f "${CA_EDMONTON_PROVIDER_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        <!-- EDMONTON PROVIDER -->
        <provider
            android:name="org.mtransit.android.commons.provider.CaEdmontonProvider"
            android:authorities="@string/ca_edmonton_authority"
            android:exported="true"
            android:readPermission="\${permission_provider_read}"
            tools:ignore="MissingRegistered">
            <meta-data
                android:name="@string/status_provider"
                android:value="@string/status_provider" />
            <meta-data
                android:name="@string/status_provider_target"
                android:value="@string/ca_edmonton_status_for_poi_authority" />
        </provider>
EOL
fi

CA_GRAND_RIVER_TRANSIT_PROVIDER_FILE="${RES_VALUES_DIR}/grand_river_transit_values.xml";
if [ -f "${CA_GRAND_RIVER_TRANSIT_PROVIDER_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        <!-- GRAND RIVER TRANSIT PROVIDER -->
        <provider
            android:name="org.mtransit.android.commons.provider.GrandRiverTransitProvider"
            android:authorities="@string/grand_river_transit_authority"
            android:exported="true"
            android:readPermission="\${permission_provider_read}"
            tools:ignore="MissingRegistered">
            <meta-data
                android:name="@string/status_provider"
                android:value="@string/status_provider" />
            <meta-data
                android:name="@string/status_provider_target"
                android:value="@string/grand_river_transit_status_for_poi_authority" />
        </provider>
EOL
fi

RSS_FILE="${RES_VALUES_DIR}/rss_values.xml";
if [ -f "${RSS_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        <!-- RSS NEWS PROVIDER -->
        <provider
            android:name="org.mtransit.android.commons.provider.RSSNewsProvider"
            android:authorities="@string/rss_authority"
            android:exported="true"
            android:readPermission="\${permission_provider_read}"
            tools:ignore="MissingRegistered">
            <meta-data
                android:name="@string/news_provider"
                android:value="@string/news_provider" />
            <meta-data
                android:name="@string/news_provider_target"
                android:value="@string/rss_target_for_poi_authority" />
        </provider>
EOL
fi

TWITTER_FILE="${RES_VALUES_DIR}/twitter_values.xml";
if [ -f "${TWITTER_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        <!-- TWITTER NEWS PROVIDER -->
        <provider
            android:name="org.mtransit.android.commons.provider.TwitterNewsProvider"
            android:authorities="@string/twitter_authority"
            android:exported="true"
            android:readPermission="\${permission_provider_read}"
            tools:ignore="MissingRegistered">
            <meta-data
                android:name="@string/news_provider"
                android:value="@string/news_provider" />
            <meta-data
                android:name="@string/news_provider_target"
                android:value="@string/twitter_target_for_poi_authority" />
        </provider>
EOL
fi

YOUTUBE_FILE="${RES_VALUES_DIR}/youtube_values.xml";
if [ -f "${YOUTUBE_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        <!-- YOUTUBE NEWS PROVIDER -->
        <provider
            android:name="org.mtransit.android.commons.provider.YouTubeNewsProvider"
            android:authorities="@string/youtube_authority"
            android:exported="true"
            android:readPermission="\${permission_provider_read}"
            tools:ignore="MissingRegistered">
            <meta-data
                android:name="@string/news_provider"
                android:value="@string/news_provider" />
            <meta-data
                android:name="@string/news_provider_target"
                android:value="@string/youtube_target_for_poi_authority" />
        </provider>
EOL
fi

INSTAGRAM_FILE="${RES_VALUES_DIR}/instagram_values.xml";
if [ -f "${INSTAGRAM_FILE}" ]; then
  cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
        <!-- INSTAGRAM NEWS PROVIDER -->
        <provider
            android:name="org.mtransit.android.commons.provider.InstagramNewsProvider"
            android:authorities="@string/instagram_authority"
            android:exported="true"
            android:readPermission="\${permission_provider_read}"
            tools:ignore="MissingRegistered">
            <meta-data
                android:name="@string/news_provider"
                android:value="@string/news_provider" />
            <meta-data
                android:name="@string/news_provider_target"
                android:value="@string/instagram_target_for_poi_authority" />
        </provider>
EOL
fi

cat >>"${ANDROID_MANIFEST_FILE}" <<EOL
    </application>
</manifest>
EOL

if [[ ${IS_CI} = true ]]; then
    echo "---------------------------------------------------------------------------------------------------------------"
    cat "${ANDROID_MANIFEST_FILE}"; #DEBUG
    echo "---------------------------------------------------------------------------------------------------------------"
fi

echo ">> Generating AndroidManifest.xml... DONE";