#!/bin/bash

function setFeatureFlags() {

  echo "> Feature flags:"

  # F_EXPORT_VEHICLE_LOCATION_PROVIDER=false
  F_EXPORT_VEHICLE_LOCATION_PROVIDER=true
  echo "> - F_EXPORT_VEHICLE_LOCATION_PROVIDER: '$F_EXPORT_VEHICLE_LOCATION_PROVIDER'."

  # F_EXPORT_GTFS_RT_TRIP_UPDATES_PROVIDER=false
  F_EXPORT_GTFS_RT_TRIP_UPDATES_PROVIDER=true
  echo "> - F_EXPORT_GTFS_RT_TRIP_UPDATES_PROVIDER: '$F_EXPORT_GTFS_RT_TRIP_UPDATES_PROVIDER'."

}
