#!/bin/bash
SCRIPT_DIR="$(dirname "$0")";

ROOT_DIR="$SCRIPT_DIR/../../../../../../..";
COMMONS_DIR="${ROOT_DIR}/commons";
source ${COMMONS_DIR}/commons.sh;

setIsCI;

setGitProjectName;

echo ">> Generating mipmap-*/module_app_icon.[png|xml]...";

APP_ANDROID_DIR="${ROOT_DIR}/app-android";
SRC_DIR="${APP_ANDROID_DIR}/src";
MAIN_DIR="${SRC_DIR}/main";
RES_DIR="${MAIN_DIR}/res";
VALUES_DIR="${RES_DIR}/values"
mkdir -p "${VALUES_DIR}";
checkResult $?;

### values/module_app_icon_color.xml - START

COLOR_FILE_NAME_XML="module_app_icon_color.xml"
COLOR_FILE_XML="${VALUES_DIR}/${COLOR_FILE_NAME_XML}";
if [ -f "${COLOR_FILE_XML}" ]; then
  echo ">> File '$COLOR_FILE_XML' already exist."; # compat with existing values/module_app_icon_color.xml
else
  requireCommand "xmllint" "libxml2-utils";
  requireCommand "jq";
  GTFS_RDS_VALUES_GEN_FILE="$VALUES_DIR/gtfs_rts_values_gen.xml"; # do not change to avoid breaking compat w/ old modules
  BIKE_STATION_VALUES_FILE="$VALUES_DIR/bike_station_values.xml";
  AGENCY_JSON_FILE="$ROOT_DIR/config/gtfs/agency.json";
  COLOR=""
  if [ -f $GTFS_RDS_VALUES_GEN_FILE ]; then #1st because color computed
    echo "> Agency file: '$GTFS_RDS_VALUES_GEN_FILE'."
    COLOR=$(xmllint --xpath "//resources/string[@name='gtfs_rts_color']/text()" "$GTFS_RDS_VALUES_GEN_FILE")
  elif [ -f $AGENCY_JSON_FILE ]; then
    echo "> Agency file: '$AGENCY_JSON_FILE'."
    COLOR=$(jq -r '.default_color // empty' "$AGENCY_JSON_FILE")
  elif [ -f $BIKE_STATION_VALUES_FILE ]; then
    echo "> Agency file: '$BIKE_STATION_VALUES_FILE'."
    COLOR=$(xmllint --xpath "//resources/string[@name='bike_station_color']/text()" "$BIKE_STATION_VALUES_FILE")
  else
    echo "> No agency file! (rds:$GTFS_RDS_VALUES_GEN_FILE|json:$AGENCY_JSON_FILE|bike:$BIKE_STATION_VALUES_FILE)"
    exit 1 # error
  fi
  echo " - color: $COLOR"
  if [ -z "$COLOR" ]; then
    echo " > No color found for agency type!"
    exit 1 # error
  fi
  rm -f "${COLOR_FILE_XML}";
  checkResult $?;
  touch "${COLOR_FILE_XML}";
  checkResult $?;
  cat >>"${COLOR_FILE_XML}" <<EOL
<?xml version="1.0" encoding="utf-8"?>
<!-- DO NOT EDIT: this file is generated by mtransitapps/commons:shared-modules/app-android/src/main/res/MTmipmap-MTSTAR/MTmodule_app_icon.MTSTAR.MT.sh -->
<resources>
    <color name="module_app_icon_color">#${COLOR}</color>
</resources>
EOL
  if [[ ${DEBUGING} = true ]]; then
      echoDebug "---------------------------------------------------------------------------------------------------------------"
      cat "${COLOR_FILE_XML}"; #DEBUG
      echoDebug "---------------------------------------------------------------------------------------------------------------"
  fi
fi

### values/module_app_icon_color.xml - END

### mipmap-anydpi-v26/module_app_icon.xml - START

FILE_NAME_XML="module_app_icon.xml"
MIPMAP_ANYDPI="${RES_DIR}/mipmap-anydpi-v26"
mkdir -p "${MIPMAP_ANYDPI}";
checkResult $?;
FILE_XML="${MIPMAP_ANYDPI}/${FILE_NAME_XML}";
if [ -f "${FILE_XML}" ]; then
  echo ">> File '$FILE_XML' already exist."; # compat with existing mipmap-anydpi-v26/module_app_icon.xml
else
  rm -f "${FILE_XML}";
  checkResult $?;
  touch "${FILE_XML}";
  checkResult $?;
  cat >>"${FILE_XML}" <<EOL
<?xml version="1.0" encoding="utf-8"?>
<!-- DO NOT EDIT: this file is generated by mtransitapps/commons:shared-modules/app-android/src/main/res/MTmipmap-MTSTAR/MTmodule_app_icon.MTSTAR.MT.sh -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/module_app_icon_color" />
    <foreground android:drawable="@mipmap/module_app_icon_foreground" />
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />
</adaptive-icon>
EOL
  if [[ ${DEBUGING} = true ]]; then
      echoDebug "---------------------------------------------------------------------------------------------------------------"
      cat "${FILE_XML}"; #DEBUG
      echoDebug "---------------------------------------------------------------------------------------------------------------"
  fi
fi

$ROOT_DIR/commons-android/pub/module-res-mipmap-launcher-icon-adaptive.sh;
checkResult $?;

### mipmap-anydpi-v26/module_app_icon.xml - END

### mipmap-*/module_app_icon.png - START

REQUIRED_ICON_FILE="${MAIN_DIR}/play/listings/en-US/graphics/icon/1.png";
if [ ! -f "$REQUIRED_ICON_FILE" ]; then
    $ROOT_DIR/commons/shared-modules/app-android/src/main/play/listings/en-US/graphics/icon/MT1.png.MT.sh;
    checkResult $?;
fi

FILE_NAME="module_app_icon.png";
for DENSITY in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
  MIPMAP_DIR="${RES_DIR}/mipmap-${DENSITY}"
  FILE_PNG="${MIPMAP_DIR}/${FILE_NAME}"
  mkdir -p "${MIPMAP_DIR}"
  checkResult $?;
  if [ -f "${FILE_PNG}" ]; then
    if [[ ${MT_GENERATE_IMAGES} != true ]]; then
      echo ">> File '$FILE_PNG' already exist."; # compat with existing mipmap-*/module_app_icon.png
      exit 0; # compat w/ manually created file
    else
      echo ">> File '$FILE_PNG' already exist: overriding image... (MT_GENERATE_IMAGES=$MT_GENERATE_IMAGES)";
      rm -f "${FILE_PNG}";
      checkResult $?;
    fi
  fi
done

$ROOT_DIR/commons-android/pub/module-res-mipmap-launcher-icon.sh;
checkResult $?;

### mipmap-*/module_app_icon.png - END

echo ">> Generating mipmap-*/module_app_icon.[png|xml]... DONE";
