#!/bin/bash
SCRIPT_DIR="$(dirname "$0")";

ROOT_DIR="$SCRIPT_DIR/../..";
COMMONS_DIR="${ROOT_DIR}/commons";
source ${COMMONS_DIR}/commons.sh;

setGitProjectName;

setIsCI;

echo ">> Generating project_name.properties...";

PROJECT_NAME_FILE="${ROOT_DIR}/project_name.properties";

if [ -f "${PROJECT_NAME_FILE}" ]; then
  echo ">> File '$PROJECT_NAME_FILE' already exist."; # compat with existing project_name.properties
  exit 0;
fi

rm -f "${PROJECT_NAME_FILE}";
checkResult $?;
touch "${PROJECT_NAME_FILE}";
checkResult $?;

PROJECT_NAME_VALUE="MT";

COUNTRY_CODE=$(echo "$PROJECT_NAME" | cut -d- -f1);
COUNTRY_CODE=${COUNTRY_CODE^^}
PROJECT_NAME_VALUE=$PROJECT_NAME_VALUE-$COUNTRY_CODE;

INDEX=2;
while true; do
  ITEM=$(echo "$PROJECT_NAME" | cut -d- -f$INDEX);
  if [ $ITEM = "android" ]; then
    ITEM="";
  fi
  if [ -z "$ITEM" ]; then
    break;
  fi
  ITEM=${ITEM^}
  PROJECT_NAME_VALUE="${PROJECT_NAME_VALUE}-${ITEM}";
  ((INDEX++))
done

echo "# DO NOT EDIT: this file is generated by MTproject_name.properties.MT.sh" >> ${PROJECT_NAME_FILE};
echo "project.name=$PROJECT_NAME_VALUE" >> ${PROJECT_NAME_FILE};

if [[ ${IS_CI} = true ]]; then
  echo "---------------------------------------------------------------------------------------------------------------";
  cat "${PROJECT_NAME_FILE}"; #DEBUG
  echo "---------------------------------------------------------------------------------------------------------------";
fi

echo ">> Generating project_name.properties... DONE";