#!/bin/bash
SCRIPT_DIR="$(dirname "$0")";

ROOT_DIR="$SCRIPT_DIR/../..";
COMMONS_DIR="${ROOT_DIR}/commons";
source ${COMMONS_DIR}/commons.sh;

echo "Generating project_name.properties...";

PROJECT_NAME_FILE="${ROOT_DIR}/project_name.properties";

if [ -f "${PROJECT_NAME_FILE}" ]; then
  echo "File '$PROJECT_NAME_FILE' already exist."; # compat with existing project_name.properties
  exit 0;
fi

rm -f "${PROJECT_NAME_FILE}";
checkResult $?;
touch "${PROJECT_NAME_FILE}";
checkResult $?;

PROJECT_NAME="MT";

REPO=$(git -C ${ROOT_DIR} config --get remote.origin.url | cut -d/ -f2 | cut -d. -f1);
echo "Git repository name: '$REPO'.";
COUNTRY_CODE=$(echo "$REPO" | cut -d- -f1);
COUNTRY_CODE=${COUNTRY_CODE^^}
PROJECT_NAME=$PROJECT_NAME-$COUNTRY_CODE;

INDEX=2;
while true; do
  ITEM=$(echo "$REPO" | cut -d- -f$INDEX);
  if [ $ITEM = "android" ]; then
    ITEM="";
  fi
  if [ -z "$ITEM" ]; then
    break;
  fi
  ITEM=${ITEM^}
  PROJECT_NAME="${PROJECT_NAME}-${ITEM}";
  ((INDEX++))
done

echo "Project name: '$PROJECT_NAME'.";

echo "# DO NOT EDIT: this file is generated by MTproject_name.properties.MT.sh" >> ${PROJECT_NAME_FILE};
echo "project.name=$PROJECT_NAME" >> ${PROJECT_NAME_FILE};

# echo "---------------------------------------------------------------------------------------------------------------";
# cat "${PROJECT_NAME_FILE}"; #DEBUG
# echo "---------------------------------------------------------------------------------------------------------------";

echo "Generating project_name.properties... DONE";