#!/bin/bash
SCRIPT_DIR="$(dirname "$0")";

ROOT_DIR="$SCRIPT_DIR/../..";
COMMONS_DIR="${ROOT_DIR}/commons";
source ${COMMONS_DIR}/commons.sh;

setIsCI;

echo ">> Generating README.md...";

README_FILE="${ROOT_DIR}/README.md";

if [ -f "${README_FILE}" ]; then
  echo ">> File '$README_FILE' already exist."; # compat with existing README.md
  exit 0;
fi

rm -f "${README_FILE}";
checkResult $?;
touch "${README_FILE}";
checkResult $?;


CONFIG_DIR="${ROOT_DIR}/config";
if [ ! -d "$CONFIG_DIR" ]; then
    echo "$CONFIG_DIR doesn't exist!";
    exit 1;
fi

AGENCY_NAME_FILE="${CONFIG_DIR}/agency_name";
if [ ! -f "$AGENCY_NAME_FILE" ]; then
    echo "$AGENCY_NAME_FILE doesn't exist!";
    exit 1;
fi

AGENCY_NAME_LONG=$(tail -n 1 $AGENCY_NAME_FILE);
if [ -z "$AGENCY_NAME_LONG" ]; then
    echo "$AGENCY_NAME_LONG is empty!";
    exit 1;
fi

AGENCY_LABEL=$AGENCY_NAME_LONG;

PARENT_AGENCY_NAME_FILE="$CONFIG_DIR/parent_agency_name";
if [ -f "$PARENT_AGENCY_NAME_FILE" ]; then
    PARENT_AGENCY_NAME_LONG=$(tail -n 1 $PARENT_AGENCY_NAME_FILE);
    if [ ! -z "$PARENT_AGENCY_NAME_LONG" ]; then
        AGENCY_LABEL="$AGENCY_LABEL ($PARENT_AGENCY_NAME_LONG)";
    fi
fi

PKG_FILE="${CONFIG_DIR}/pkg";
if [ ! -f "$PKG_FILE" ]; then
    echo "$PKG_FILE doesn't exist!";
    exit 1;
fi

PKG=$(head -n 1 $PKG_FILE);
if [ -z "$PKG" ]; then
    echo "$PKG is empty!";
    exit 1;
fi

cat >>"${README_FILE}" <<EOL
<!-- DO NOT EDIT: this file is generated by MTREADME.md.MT.sh -->
# $AGENCY_LABEL for [MonTransit](https://github.com/mtransitapps/mtransit-for-android)

<img width="25%" height="25%" src="app-android/src/main/play/listings/en-US/graphics/icon/1.png"/>

## Download on Google Play

<a href="https://play.google.com/store/apps/details?id=$PKG"><img width="25%" height="25%" src="https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png"/></a>

## Screenshots

<p float="left">
<img width="25%" height="25%" src="app-android/src/main/play/listings/en-US/graphics/phone-screenshots/1.png"/>
<img width="25%" height="25%" src="app-android/src/main/play/listings/en-US/graphics/phone-screenshots/2.png"/>
<img width="25%" height="25%" src="app-android/src/main/play/listings/en-US/graphics/phone-screenshots/3.png"/>
</p>

## Social

* [Facebook](https://www.facebook.com/MonTransit)

* [Twitter](https://twitter.com/montransit)

## BETA program

Learn more about the BETA program [here](https://github.com/mtransitapps/mtransit-for-android/wiki/BETA)

## License

* [Apache Version 2.0](http://www.apache.org/licenses/LICENSE-2.0.html)
EOL

if [[ ${IS_CI} = true ]]; then
    echo "---------------------------------------------------------------------------------------------------------------";
    cat "${README_FILE}"; #DEBUG
    echo "---------------------------------------------------------------------------------------------------------------";
fi

echo ">> Generating README.md... DONE";