# Dependabot file location is: gradle/libs.versions.toml
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#gradle
[versions]
# Android 5.0 Lollipop
minSdkVersion = "21" # TODO sdkversion-min...
# Android 13 Tiramisu
targetSdkVersion = "33"
# Android 13 Tiramisu
compileSdkVersion = "33"
# https://maven.google.com/
# Android 13 Tiramisu
buildToolsVersion = "33.0.2"
kotlinOptionsJvmTarget = "17"
# https://github.com/JetBrains/kotlin/releases/latest
kotlinVersion = "1.8.21"
# https://github.com/Kotlin/kotlinx.coroutines/releases/latest
kotlinCoroutinesVersion = "1.7.1"
# https://plugins.gradle.org/plugin/org.sonarqube
sonarVersion = "3.4.0.2513"
# https://developer.android.com/studio/releases/gradle-plugin
androidGradlePluginVersion = "8.0.1"
# https://github.com/Triple-T/gradle-play-publisher/releases/latest
playPublisherVersion = "3.8.3"
benManesVersionsVersion = "0.46.0"
littlerobotsVersionCatalogVersion = "0.8.0"
# https://github.com/google/dagger/releases/latest
hiltVersion = "2.46.1"
# ALL: https://developer.android.com/jetpack/androidx/versions
# LATEST: https://developer.android.com/jetpack/androidx/versions/stable-channel
activityVersion = "1.7.1"
annotationVersion = "1.6.0"
appCompatVersion = "1.6.1"
browserVersion = "1.5.0"
cardViewVersion = "1.0.0"
coordinatorVersion = "1.2.0"
constraintVersion = "2.1.4"
coreVersion = "1.10.1"
coreSpashscreenVersion = "1.0.1"
fragmentVersion = "1.5.7"
lifecycleVersion = "2.6.1"
navigationVersion = "2.5.3"
prefVersion = "1.2.0"
recyclerviewVersion = "1.3.0"
roomVersion = "2.5.1"
slidePanelLayoutVersion = "1.2.0"
swipeRefreshLayoutVersion = "1.1.0"
vectorDrawableVersion = "1.1.0"
viewPager2Version = "1.0.0"
workManagerVersion = "2.8.1"
# https://github.com/material-components/material-components-android/releases/latest
materialVersion = "1.9.0"
# https://github.com/googlemaps/android-maps-utils/releases/latest
# https://search.maven.org/artifact/com.google.maps.android/android-maps-utils
# https://repo1.maven.org/maven2/com/google/maps/android/android-maps-utils/
mapsUtilsVersion = "3.4.0"
# https://github.com/googlemaps/android-maps-ktx/releases/latest
mapsKtxVersion = "3.4.0"
# https://developers.google.com/android/guides/google-services-plugin
gpsPluginVersion = "4.3.15"
# LATEST: https://developers.google.com/android/guides/releases
adsMediationTestSuiteVersion = "3.0.0"
playServicesAdsVersion = "22.0.0"
playServicesBasementVersion = "18.2.0"
playServicesLocationVersion = "21.0.1"
playServicesMapsVersion = "18.1.0"
# LATEST: https://firebase.google.com/support/release-notes/android#latest_sdk_versions
# ALL: https://firebase.google.com/support/releases
firebaseBomVersion = "32.0.0"
firebaseCrashlyticsPluginVersion = "2.9.5"
billingVersion = "6.0.0"
# https://developer.android.com/guide/playcore/in-app-updates/kotlin-java#setup
# https://developer.android.com/guide/playcore#java-kotlin-in-app-review
googlePlayAppUpdateLibVersion = "2.0.1"
# https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/android/changelog
# facebookSdkVersion = "6.11.0" # included with nediation adapter
facebookMediationSdkVersion = "6.14.0.0"
# https://github.com/AppLovin/AppLovin-MAX-SDK-Android/releases/latest
# appLovinSdkVersion = "11.5.2" # included with nediation adapter
appLovinMediationSdkVersion = "11.9.0.0"
# https://github.com/square/leakcanary/releases
leakCanaryVersion = "2.10"
# https://github.com/protocolbuffers/protobuf/releases/latest
# https://github.com/protocolbuffers/protobuf/tree/main/java#gradle
# https://github.com/protocolbuffers/protobuf/blob/main/java/lite.md
protobufVersion = "3.23.0"
# https://github.com/google/protobuf-gradle-plugin/releases/latest
protobufPluginVersion = "0.9.3"
# https://github.com/square/retrofit/tags
# https://github.com/square/retrofit/releases/latest
retrofitVersion = "2.9.0"
# https://github.com/square/okhttp/tags
# https://github.com/square/okhttp/releases/latest
# https://square.github.io/okhttp/changelog/
okHttpVersion = "4.11.0"
# https://github.com/google/gson/releases/latest
# https://github.com/google/gson/blob/master/CHANGELOG.md
gsonVersion = "2.10.1"
# https://github.com/bumptech/glide/releases/latest
glideVersion = "4.15.1"
# https://bigbadaboom.github.io/androidsvg/release_notes.html
# https://github.com/BigBadaboom/androidsvg/releases/latest
androidSVGVersion = "1.4"
# https://mvnrepository.com/artifact/junit/junit
jUnitVersion = "4.13.2"
# https://mvnrepository.com/artifact/org.mockito/mockito-core
mockitoVersion = "5.3.1"
# https://commons.apache.org/
commonsCSVVersion = "1.10.0"
commonsIOVersion = "2.11.0"
commonsLang3Version = "3.12.0"
commonsTextVersion = "1.10.0"
# https://github.com/xerial/sqlite-jdbc/releases/latest
xerialSQLiteJDBCVersion = "3.41.2.1"

[libraries]
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinVersion" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutinesVersion" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutinesVersion" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePluginVersion" }
playPublisherPlugin = { module = "com.github.triplet.gradle:play-publisher", version.ref = "playPublisherVersion" }
# benManesVersions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "benManesVersionsVersion" }
# littlerobotsVersionCatalog = { module = "nl.littlerobots.vcu:plugin", version.ref = "littlerobotsVersionCatalogVersion" }
sonar-plugin = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref = "sonarVersion" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
# hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltVersion" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activityVersion" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotationVersion" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompatVersion" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browserVersion" }
androidx-cardView = { module = "androidx.cardview:cardview", version.ref = "cardViewVersion" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorVersion" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintVersion" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "coreVersion" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSpashscreenVersion" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentVersion" }
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleVersion" }
androidx-lifecycle-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleVersion" }
androidx-nav-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationVersion" }
androidx-nav-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationVersion" }
androidx-pref = { module = "androidx.preference:preference-ktx", version.ref = "prefVersion" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
androidx-room = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-slidingpanelayout = { module = "androidx.slidingpanelayout:slidingpanelayout", version.ref = "slidePanelLayoutVersion" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefreshLayoutVersion" }
androidx-vectordrawable = { module = "androidx.vectordrawable:vectordrawable", version.ref = "vectorDrawableVersion" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
androidx-viewmodel-state = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycleVersion" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewPager2Version" }
androidx-workManager-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "workManagerVersion" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycleVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
# gpsPlugin = { module = "com.google.gms:google-services", version.ref = "gpsPluginVersion" }
# mediationTestSuite = { module = "com.google.android.ads:mediation-test-suite", version.ref = "adsMediationTestSuiteVersion"} # adds WRITE_EXTERNAL_STORAGE, READ_PHONE_STATE...
gps-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAdsVersion" }
gps-basement = { module = "com.google.android.gms:play-services-basement", version.ref = "playServicesBasementVersion" }
gps-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }
gps-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMapsVersion" }
maps-ktx = { module = "com.google.maps.android:maps-ktx", version.ref = "mapsKtxVersion" }
maps-utils = { module = "com.google.maps.android:android-maps-utils", version.ref = "mapsUtilsVersion" }
maps-utils-ktx = { module = "com.google.maps.android:maps-utils-ktx", version.ref = "mapsKtxVersion" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-crashlytics-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPluginVersion" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
play-billing = { module = "com.android.billingclient:billing-ktx", version.ref = "billingVersion" }
play-appUpdate = { module = "com.google.android.play:app-update-ktx", version.ref = "googlePlayAppUpdateLibVersion" }
# fbAudienceNetwork = { module = "com.facebook.android:audience-network-sdk", version.ref = "facebookSdkVersion" } # included with nediation adapter
fbAudienceNetwork-mediation = { module = "com.google.ads.mediation:facebook", version.ref = "facebookMediationSdkVersion" }
# appLovin = { module = "com.applovin:applovin-sdk", version.ref = "appLovinSdkVersion" } # included with nediation adapter
appLovin-mediation = { module = "com.google.ads.mediation:applovin", version.ref = "appLovinMediationSdkVersion" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanaryVersion" }
protobuf-compiler = { module = "com.google.protobuf:protoc", version.ref = "protobufVersion" }
protobuf-javaLite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufVersion" }
protobuf-plugin = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobufPluginVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
retrofit-gsonConverter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okHttpVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideVersion" }
android-svg = { module = "com.caverock:androidsvg-aar", version.ref = "androidSVGVersion" }
jUnit = { module = "junit:junit", version.ref = "jUnitVersion" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoVersion" }
commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "commonsCSVVersion" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIOVersion" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3Version" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commonsTextVersion" }
xerial-sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "xerialSQLiteJDBCVersion" }

[bundles]
kotlin = [
    "kotlin-coroutines",
]
kotlin-android = [
    "kotlin-coroutines-android",
]
androidx = [
    "androidx-activity",
    "androidx-annotation",
    "androidx-appCompat",
    "androidx-browser",
    "androidx-cardView",
    "androidx-constraintLayout",
    "androidx-coordinatorlayout",
    "androidx-core",
    "androidx-core-splashscreen",
    "androidx-fragment",
    "androidx-lifecycle-java8",
    "androidx-livedata",
    "androidx-nav-fragment",
    "androidx-nav-ui",
    "androidx-pref",
    "androidx-recyclerview",
    "androidx-room",
    "androidx-room-runtime",
    "androidx-slidingpanelayout",
    "androidx-swiperefreshlayout",
    "androidx-vectordrawable",
    "androidx-viewmodel",
    "androidx-viewmodel-state",
    "androidx-viewpager2",
]
workManager = [
    "androidx-workManager-runtime",
]
dagger = [
    "hilt",
]
gps = [
    "firebase-analytics",
    "firebase-crashlytics",
    "gps-ads",
    "gps-basement",
    "gps-location",
    "gps-maps",
    "maps-ktx",
    "maps-utils",
    "maps-utils-ktx",
]
gpsPlatform = [
    "firebase-bom",
]
billingClient = [
    "play-billing",
]
googlePlay = [
    "play-appUpdate",
]
fb = [
    "fbAudienceNetwork-mediation",
]
appLovin = [
    "appLovin-mediation",
]
leakCanary = [
    "leakcanary",
]
retrofit = [
    "retrofit",
    "retrofit-gsonConverter",
]
okHttp = [
    "okhttp",
    "okhttp-loggingInterceptor",
]
gson = [
    "gson",
]
img = [
    "android-svg",
    "glide",
]
jUnit = [
    "jUnit",
]
mockito = [
    "mockito-core",
]
commons = [
    "commons-csv",
    "commons-io",
    "commons-lang3",
    "commons-text",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePluginVersion" }
android-library = { id = "com.android.library", version.ref = "androidGradlePluginVersion" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPluginVersion" }
gms = { id = "com.google.gms.google-services", version.ref = "gpsPluginVersion" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinVersion" }
triplet-playPublisher = { id = "com.github.triplet.play", version.ref = "playPublisherVersion" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPluginVersion" }
benmanes-versions = { id = "com.github.ben-manes.versions", version.ref = "benManesVersionsVersion" }
littlerobots-versioncatalog = { id = "nl.littlerobots.version-catalog-update", version.ref = "littlerobotsVersionCatalogVersion" }
sonar = { id = "org.sonarqube", version.ref = "sonarVersion" }