#!/bin/bash
SCRIPT_DIR="$(dirname "$0")";

ROOT_DIR="$SCRIPT_DIR/../../../../../../..";
COMMONS_DIR="${ROOT_DIR}/commons";
source ${COMMONS_DIR}/commons.sh;

setGitProjectName;

setIsCI;

echo ">> Generating parent_agency_values.xml...";

APP_ANDROID_DIR="${ROOT_DIR}/app-android";
SRC_DIR="${APP_ANDROID_DIR}/src";
MAIN_DIR="${SRC_DIR}/main";
RES_DIR="${MAIN_DIR}/res";
VALUES_DIR="${RES_DIR}/values";
PARENT_AGENCY_VALUES="${VALUES_DIR}/parent_agency_values.xml";
mkdir -p "${VALUES_DIR}";
checkResult $?;
if [ -f "${PARENT_AGENCY_VALUES}" ]; then
  echo ">> File '$PARENT_AGENCY_VALUES' already exist."; # compat with existing parent_agency_values.xml
  exit 0; # compat w/ manually created file
fi

rm -f "${PARENT_AGENCY_VALUES}";
checkResult $?;

CONFIG_DIR="${ROOT_DIR}/config";
if [ ! -d "$CONFIG_DIR" ]; then
    echo "$CONFIG_DIR doesn't exist!";
    exit 1;
fi

PARENT_AGENCY_NAME_SHORT="";
PARENT_AGENCY_NAME_FILE="$CONFIG_DIR/parent_agency_name";
if [ -f "$PARENT_AGENCY_NAME_FILE" ]; then
    PARENT_AGENCY_NAME_SHORT=$(head -n 1 $PARENT_AGENCY_NAME_FILE);
fi

PARENT_AGENCY_COLOR="";
PARENT_AGENCY_COLOR_FILE="$CONFIG_DIR/parent_agency_color";
if [ -f "$PARENT_AGENCY_COLOR_FILE" ]; then
    PARENT_AGENCY_COLOR=$(head -n 1 $PARENT_AGENCY_COLOR_FILE);
fi

if [[ -z "$PARENT_AGENCY_NAME_SHORT" && -z "$PARENT_AGENCY_COLOR" ]]; then
  echo ">> Generating parent_agency_values.xml... SKIP (no parent agency name or color defined)";
  exit 0; # ok
fi

touch "${PARENT_AGENCY_VALUES}";
checkResult $?;

cat >>"${PARENT_AGENCY_VALUES}" <<EOL
<?xml version="1.0" encoding="utf-8"?>
<!-- DO NOT EDIT: this file is generated by MTparent_agency_values.xml.MT.sh -->
<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation,UnusedResources">
    <string name="parent_agency_short_name">$PARENT_AGENCY_NAME_SHORT</string>
    <string name="parent_agency_color">$PARENT_AGENCY_COLOR</string>
</resources>
EOL

if [[ ${IS_CI} = true ]]; then
  echo "---------------------------------------------------------------------------------------------------------------";
  cat "${PARENT_AGENCY_VALUES}"; #DEBUG
  echo "---------------------------------------------------------------------------------------------------------------";
fi

echo ">> Generating parent_agency_values.xml... DONE";