#!/bin/bash
SCRIPT_DIR="$(dirname "$0")";

ROOT_DIR="$SCRIPT_DIR/../../../../../../..";
COMMONS_DIR="${ROOT_DIR}/commons";
source ${COMMONS_DIR}/commons.sh;

setGitProjectName;

setIsCI;

echo ">> Generating values-fr/bike_station_strings.xml...";

APP_ANDROID_DIR="${ROOT_DIR}/app-android";
SRC_DIR="${APP_ANDROID_DIR}/src";
MAIN_DIR="${SRC_DIR}/main";
RES_DIR="${MAIN_DIR}/res";
VALUES_FR_DIR="${RES_DIR}/values-fr";

LANG_FR_FILE="${ROOT_DIR}/config/lang/fr";
if [ ! -f "$LANG_FR_FILE" && ! -d "$VALUES_FR_DIR" ]; then
    echo ">> Generating values-fr/bike_station_strings.xml... SKIP (FR lang not supported)";
    exit 0; # ok
fi

BIKE_STATION_VALUES_FILE="${ROOT_DIR}/app-android/src/main/res/values/bike_station_values.xml";
if [ ! -f "${BIKE_STATION_VALUES_FILE}" ]; then
    echo ">> Generating values-fr/bike_station_strings.xml... SKIP (not an Bike station agency)";
    exit 0; # ok
fi

BIKE_STATION_STRINGS_FILE="${VALUES_FR_DIR}/bike_station_strings.xml";
mkdir -p "${VALUES_FR_DIR}";
checkResult $?;
if [ -f "${BIKE_STATION_STRINGS_FILE}" ]; then
  echo ">> File '$BIKE_STATION_STRINGS_FILE' already exist."; # compat with existing values-fr/bike_station_strings.xml
  exit 0; # compat w/ manually created file
fi

rm -f "${BIKE_STATION_STRINGS_FILE}";
checkResult $?;
touch "${BIKE_STATION_STRINGS_FILE}";
checkResult $?;

CONFIG_DIR="${ROOT_DIR}/config";
if [ ! -d "$CONFIG_DIR" ]; then
    echo "$CONFIG_DIR doesn't exist!";
    exit 1;
fi

AGENCY_NAME_FILE="${CONFIG_DIR}/agency_name";
if [ ! -f "$AGENCY_NAME_FILE" ]; then
    echo "$AGENCY_NAME_FILE doesn't exist!";
    exit 1;
fi

AGENCY_NAME_LONG=$(tail -n 1 $AGENCY_NAME_FILE);
if [ -z "$AGENCY_NAME_LONG" ]; then
    echo "$AGENCY_NAME_LONG is empty!";
    exit 1;
fi

AGENCY_NAME_SHORT=$(head -n 1 $AGENCY_NAME_FILE);
if [ -z "$AGENCY_NAME_SHORT" ]; then
    echo "$AGENCY_NAME_SHORT is empty!";
    exit 1;
fi

requireCommand "xmllint" "libxml2-utils";

TYPE=-1;
if [ -f $BIKE_STATION_VALUES_FILE ]; then
  TYPE=$(xmllint --xpath "//resources/integer[@name='bike_station_agency_type']/text()" "$BIKE_STATION_VALUES_FILE")
else
  echo "> No agency file! (bike:$BIKE_STATION_VALUES_FILE)"
  exit 1 # error
fi
TYPE_LABEL="";
if [ "$TYPE" -eq 100 ]; then # BIKE
    TYPE_LABEL="Vélos";
else
  echo "Unexpected agency type '$TYPE'!"
  exit 1 # error
fi

cat >>"${BIKE_STATION_STRINGS_FILE}" <<EOL
<?xml version="1.0" encoding="utf-8"?>
<!-- DO NOT EDIT: this file is generated by MTbike_station_strings.xml.MT.sh -->
<resources>
    <string name="bike_station_label">$TYPE_LABEL $AGENCY_NAME_LONG</string>
    <string name="bike_station_short_name">$AGENCY_NAME_SHORT</string>
</resources>
EOL

if [[ ${IS_CI} = true ]]; then
  echo "---------------------------------------------------------------------------------------------------------------";
  cat "${BIKE_STATION_STRINGS_FILE}"; #DEBUG
  echo "---------------------------------------------------------------------------------------------------------------";
fi

echo ">> Generating values-fr/bike_station_strings.xml... DONE";