# Default values:
# https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml
config:
  validation: true
  warningsAsErrors: false
  excludes: [ ]

complexity:
  CyclomaticComplexMethod:
    allowedComplexity: 16 # instead of default 14
  ComplexCondition:
    allowedConditions: 4 # instead of default 3
  LargeClass:
    allowedLines: 800 # instead of default 600
  LongMethod:
    allowedLines: 80 # instead of default 60
  LongParameterList:
    allowedFunctionParameters: 6 # instead of default 5
    allowedConstructorParameters: 7 # instead of default 6
    ignoreDefaultParameters: true
  NestedBlockDepth:
    allowedDepth: 5 # instead of default 4
  TooManyFunctions:
    allowedFunctionsPerFile: 12 # instead of default 11
    allowedFunctionsPerClass: 12 # instead of default 11
    allowedFunctionsPerInterface: 12 # instead of default 11
    allowedFunctionsPerObject: 12 # instead of default 11
    allowedFunctionsPerEnum: 12 # instead of default 11

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

ktlint:
  # active: true
  maxLineLength: 160 # same as style.MaxLineLength
  ArgumentListWrapping:
    active: false # too strict, disabled (for now)
    maxLineLength: 160 # same as ktlint.maxLineLength
  BinaryExpressionWrapping:
    maxLineLength: 160 # same as ktlint.maxLineLength
  BlankLineBetweenWhenConditions:
    active: false # disabled because doesn't allow // comment on the same line
    lineBreakAfterWhenEntries: true
  ChainWrapping:
    active: false # disabled because line should be able to begin with || or &&
  ClassSignature:
    active: false # disabled because too strict:
    # - No whitespace expected between opening parenthesis and first parameter name
    # - Single whitespace expected before parameter
    # - No whitespace expected between last parameter and closing parenthesis
    maxLineLength: 160 # same as ktlint.maxLineLength
  FunctionExpressionBody:
    active: false # disabled for now because too much code change
    maxLineLength: 160 # same as ktlint.maxLineLength
  FunctionLiteral:
    active: false # disabled because doesn't allow // comment on the same line
    maxLineLength: 160 # same as ktlint.maxLineLength
  FunctionReturnTypeSpacing:
    maxLineLength: 160 # same as ktlint.maxLineLength
  FunctionSignature:
    active: false # disabled for now because too strict (either all parameters on one line or each on a separate line)
    maxLineLength: 160 # same as ktlint.maxLineLength
  Indentation:
    indentWhenArrowOnNewLine: true # Starting from IDEA version 2024.2 or above this value needs to be set to true to maintain compatibility with IDEA formatting.
  Kdoc:
    active: false # /** */ useful everywhere (can contain clickable [links] to other classes...)
  LoopWithTooManyJumpStatements:
    maxJumpCount: 2 # instead of default 1
  MaximumLineLength:
    maxLineLength: 160 # same as ktlint.maxLineLength
  ParameterListWrapping:
    maxLineLength: 160 # same as ktlint.maxLineLength
  ParameterWrapping:
    maxLineLength: 160 # same as ktlint.maxLineLength
  PropertyWrapping:
    maxLineLength: 160 # same as ktlint.maxLineLength
  StatementWrapping:
    active: false # disabled for now because too strict (disallow one-liner like 'setTouchInterceptor { _, _ -> this.dismiss(); true }')
  TrailingCommaOnCallSite:
    active: false # not mandatory
  TrailingCommaOnDeclarationSite:
    active: false # not mandatory
  ValueParameterComment:
    active: false # comments next to annoation are fine like:
    # @SerializedName("url") // added in v7.3
    # val url: String?,
  Wrapping:
    maxLineLength: 160 # same as ktlint.maxLineLength

potential-bugs:
  UnnecessarySafeCall:
    active: false # too many false positives (w/o detekt kotlin compiler plugin, IDE shows warning)

style:
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 4 # instead of default 3: MediatorLiveData with 4 sources
  MagicNumber:
    ignoreEnums: true
  MaxLineLength: # same as ktlint.maxLineLength
    maxLineLength: 160
  NewLineAtEndOfFile:
    active: false # same as ktlint.FinalNewline
  ReturnCount:
    max: 3 # instead of default 2
  ThrowsCount:
    max: 3 # instead of default 2
  UnusedImport:
    active: true # instead of default false

