name: MT Dependency Submission

on:
  workflow_dispatch: # manual
  push:
    paths:
      - "shared/gradle/wrapper/**"
      - "shared/gradlew"
      - "shared/gradlew.bat"
      - "shared/gradle.properties"
      - "gradle/libs.versions.toml"
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  mt-dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - name: MT check out main repo
      uses: actions/checkout@v5
      with:
        repository: mtransitapps/mtransit-for-android
    - name: MT check out submodules
      run: ./checkout_submodules.sh
    - name: MT code setup
      run: ./commons/code_setup.sh
    - name: MT set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
