name: "MT Validate Gradle Wrapper"
on:
  workflow_dispatch: # manual
  push:
    paths:
      - "shared/gradle/wrapper/**"
      - "shared/gradlew"
      - "shared/gradlew.bat"
      - "shared/gradle.properties"
  pull_request:
    paths:
      - "shared/gradle/wrapper/**"
      - "shared/gradlew"
      - "shared/gradlew.bat"
      - "shared/gradle.properties"

jobs:
  MT-GRADLE_WRAPPER-VALIDATION:
    name: "MT Gradle wrapper validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "MT move gradle files to default location"
        run: |
          cp -R shared/gradl* .
      - uses: gradle/actions/wrapper-validation@v4
